apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  ConnectionStrings__Postgres: "Host={{ .Release.Name }}-postgres;Database={{ .Values.postgres.database }};Username={{ .Values.postgres.username }};Password={{ .Values.secrets.postgresPassword }}"
